name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install
      working-directory: ios

    - name: Build iOS
      run: |
        flutter build ipa --release --no-codesign
